/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sound.test;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import edu.wpi.first.networktables.NetworkTable; 
import edu.wpi.first.networktables.NetworkTableEntry; 
import edu.wpi.first.networktables.NetworkTableInstance;

public class App {
    static Clip clip; 
    static Clip clip2; 

    public static void play(Clip clip) throws Exception {
        clip.start();
        clip.loop(100);
    }
    public static void stop(Clip clip) throws Exception {
      if (clip != null ) {
        clip.stop();
        clip.setFramePosition(0);

      }
    }

    
    public static void main(String[] args ) throws Exception {
      clip = AudioSystem.getClip(); 
      clip.open(AudioSystem.getAudioInputStream(ClassLoader.getSystemResourceAsStream("s_heavytankloop.wav")));
      clip2 = AudioSystem.getClip(); 
      clip2.open(AudioSystem.getAudioInputStream(ClassLoader.getSystemResourceAsStream("tankdrivein1.wav")));
    
      new App().run();
    }
    public void run() throws Exception {
        
        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        NetworkTable table = inst.getTable("datatable");
        NetworkTableEntry entry = table.getEntry("x");
        NetworkTableEntry entry2 = table.getEntry("y");
        entry2.setBoolean(false);
        entry.setBoolean(false);
        inst.startClientTeam(7028); 
        inst.startDSClient();  
 //       inst.startClient("localhost");
        while (true) {
          Thread.sleep(200);
          boolean state = entry.getBoolean(false);
          boolean state2 = entry2.getBoolean(false);

          System.out.println("Button Pressed: " + state);
          
          if (state == true) {
            if (clip2.isRunning()) {
              stop(clip2);
            }
            play(clip);
          }
          else if (state2 == true) {
            if (clip.isRunning()) {
              stop(clip);
            }
            play(clip2);
          }
          if (state == false) {
            stop(clip);
          }
          if (state2 == false) {
            stop(clip2);
          }
        }
      }
}
